version: '3'
services:
  stock-mysql:
    container_name: stock-mysql
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_DATABASE: stock_exchange
      MYSQL_ROOT_PASSWORD: password
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    restart: always
    networks:
      - app-network

  stock-app:
    container_name: stock-back
    build: ./stockExchange
    volumes:
      - ./stockExchange:/app
      - ~/.m2:/root/.m2
    working_dir: /app
    ports:
      - "8080:8080"
    command: mvn clean spring-boot:run
    depends_on:
      - stock-mysql
    restart: on-failure
    networks:
      - app-network

  traffic-mysql:
    container_name: traffic-mysql
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_DATABASE: traffic_generator
      MYSQL_ROOT_PASSWORD: password
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3307:3307"
    restart: always
    networks:
      - app-network

  traffic-app:
    container_name: traffic-back
    build: ./traffic-generator
    volumes:
      - ./traffic-generator:/app
      - ~/.m2:/root/.m2
    working_dir: /app
    ports:
      - "8081:8080"
    command: mvn clean spring-boot:run
    depends_on:
      - traffic-mysql
    restart: on-failure
    networks:
      - app-network
    
  stock-front:
    container_name: stock-front
    image: raphau/stock-front:latest
    ports:
      - "8083:80"
    networks:
      - app-network
      
networks:
  app-network:
    driver: bridge